language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master

install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - $GOPATH/bin/dep ensure

script:
  - make build